### ISSUE TITLE
Missing drivers please install nvidia proprietary driver Error Code:1

### ISSUE THREAD

**Issue by gamidov-r** [RunGp/Nvidiux#14]
driver 367.27

**Comment by andrewschott** [comment]
Do you need to reboot by chance?  I had that issue a while back, but it went away when I rebooted.

Btw I am on that exact driver with a 970 and NVIDIUX is quite happy with everything.

**Comment by gamidov-r** [comment]
about reboot on installation nothing say
I try

**Comment by steamlinux** [comment]
I try

**Comment by andrewschott** [comment]
No you normally shouldnt have to reboot, but I have noticed that when some drivers update things can get out of whack very quickly.  Namely the proprietary NV and AMD GPU drivers.

Other than that I am not sure offhand without @RunGp to offer some advice, I am just about out of any likely useful ideas.  As you may have guessed, I live in the land of Red Hat and sometimes SELinux can crop up and cause some grief.  I am sure AppArmor could too (been a very long time since I used that).  If I recall correctly, the app should complain if the needed xorg parameters are missing.  So ... yeah I am about of of ideas here.

**Comment by RunGp** [comment]
hi

Give me your linux distibution name (and version) (debian ? arch ? fedora ?) and return of
`uname -a ; ls -l /usr/lib | grep nvidia`

nvidia-settings is also installed ?

**Comment by gamidov-r** [comment]
Linux ruslan 4.6.0-1-amd64 #1 SMP Debian 4.6.2-2 (2016-06-25) x86_64 GNU/Linux
I use debian sid
ls -l /usr/lib | grep nvidia nothing return

**Comment by RunGp** [comment]
nothing...
Nvidiux use nvidia library for overclock (and get gpu info) maybe library are located in other path on debian sid( try with /usr/local/lib)
`ls -l /usr/local/lib | grep nvidia`
do you know where could be located nvidia library on your system ?

**Comment by gamidov-r** [comment]
ls -l /usr/local/lib | grep nvidia nothing return too
I try ls -l /usr/lib/i386-linux-gnu/ | grep nvidia
look output on this http://pastebin.com/D1VMnv30

**Comment by RunGp** [comment]
ok library found ;)
i had this path nvidiux will work in next minor version released probably in 2-3 week (after my traveling)

**Comment by gamidov-r** [comment]
thank's, I wait)

**Comment by RunGp** [comment]
hi 
Version 1.4.1 is released soon (after traductor give me updated lang file)
After update start nvidiux with 
nvidiux -p /usr/lib/i386-linux-gnu/
